config/routes.rb
Grxclan::Application.routes.draw do
  get "registrations/account_update_params"
  devise_for :users, :controllers => { registrations: 'registrations' }

  get "videos/index"
  get "videos/show"

  root 'static_pages#home'
  get "static_pages/about"

  resources :topics do
    member do
      post 'upvote'
    end
  end

  resources :users

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/roster', to: 'static_pages#roster',   via: 'get'
  match '/video', to: 'static_pages#video',     via: 'get'

  match '/users/:id(.:format)', to: 'users#show',   via: 'get'
  match '/users/:id', to: 'users#create',   via: 'post'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable     

  validates :gamertag, presence: true, length: { maximum: 20 }  

  has_attached_file :avatar, 
    :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:attachment/:id/:basename_:style.:extension",
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
  },
    :convert_options => {
    :thumb    => '-set colorspace sRGB -strip',
    :preview  => '-set colorspace sRGB -strip',
    :large    => '-set colorspace sRGB -strip',
    :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


#   before_save :extract_dimensions
#   serialize :dimensions  

#   def image?
#     avatar_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}
#   end
 

# private

#   def extract_dimensions
#     return unless image?
#       tempfile = avatar.queued_for_write[:original]
#     unless tempfile.nil?
#       geometry = Paperclip::Geometry.from_file(tempfile)
#       self.dimensions = [geometry.width.to_i, geometry.height.to_i]
#     end
#   end
end  

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :topic	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:gamertag, :email, :password, :password_confirmation) }

    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:email, :password, :password_confirmation, :current_password, 
                                 :gamertag, :name, :role, :occupation, :fave_game, :game_addiction, 
                                 :fave_character, :first_fps, :fave_movie, :hobbies, :fact, :twitter, 
                                 :youtube, :twitch, :avatar, :avatar_file_name, :avatar_file_size,
                                 :avatar_content_type, :avatar_updated_at, :featured_vid)
                                 
    end
  end 
end

app/controllers/profiles_controller.rb
  class ProfilesController < ApplicationController

  def index
  end

  def new
    @user = current_user
    @profile = Profile.new
  end

  def create
    if user_signed_in?
      @user = current_user
      @profile = current_user.build_profile(params[:profile])
      if @profile.save
        flash[:success] = "Profile created!"
        redirect_to @profile
      else
        flash[:error] = "Please complete your profile."
        # render new_profile_path(@profile)
      end    
    else
      flash[:success] = "else"
      # redirect_to profiles_path
    end    
  end

  def show
    @user = current_user
    @profile = Profile.find(params[:id])    
  end

  def edit
    @profile = Profile.find(params[current_user.id])
  end

  def update
  end

  def destroy
  end

private

  def correct_user
    @profile = current_user.profiles.find_by(id: params[:id])
    redirect_to root_url unless current_user?(@profile.user)
  end

  def profile_params
      # It's mandatory to specify the nested attributes that should be whitelisted.
      # If you use `permit` with just the key that points to the nested attributes hash,
      # it will return an empty hash.
    params.require(:profile).permit(:name, :role, :occupation)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, 
                                 :gamertag, :name, :role, :occupation, :fave_game, :game_addiction, 
                                 :fave_character, :first_fps, :fave_movie, :hobbies, :fact, :twitter, 
                                 :youtube, :twitch, :avatar, :avatar_file_name, :avatar_file_size,
                                 :avatar_content_type, :avatar_updated_at, :featured_vid)    
  end

protected

  def after_update_path_for(resource)
    user_path(resource)
  end   
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def roster
    @users = User.all
  end

  def video
  end

private

  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
  end

  def current_user=(user)
    @current_user = user
  end  

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

def index
  @topics = Topic.all
end

def show 

end

private

  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update]  

  def index
    @users = User.all
    @user = current_user
    render 'show'
  end

  def new
  	@user = User.new  	
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user	
      redirect_to @user
    else
      render 'new'
    end
  end    	

  def show
    @user = User.find(params[:id]) 
  end

  def edit
    @user = User.find(params[:id])  
  end  

private

  def user_params
    params.require(:user).permit(:gamertag, :name, :email, :role, :occupation, :fave_game, 
                                 :game_addiction, :fave_character, :first_fps, :fave_movie, 
                                 :hobbies, :fact, :twitter, :youtube, :twitch, :avatar,
                                 :avatar_file_name, :avatar_file_size, :avatar_content_type, 
                                 :avatar_updated_at, :featured_vid)
  end

  def current_user=(user)
    @current_user = user
  end  

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">   
      <nav>
        <li><%= link_to image_tag("GRXclanlogo.png", size: "125x75", alt: "GRX Clan", :class => 'brand'), root_path %></li>
        <ul class="nav pull-right navlinks">
          <li><%= link_to "HOME", root_path %></li>
          <li><%= link_to "ABOUT", about_path %></li>
          <li><%= link_to "ROSTER", roster_path %></li>
          <li><%= link_to "VIDEO", video_path %></li>
          <li><%= link_to "GALLERY", "#" %></li>
        
        <ul class="menu nav pull-right", id="gamertag">
          <% if signed_in? %>
            <li class="menu dropit-trigger dropit-open">
              <%= link_to "#{current_user.gamertag}", users_path, :id => 'gamertag_dropdown' %>
              <ul id='signup', class="dropit-submenu">
                <li><%=link_to "Edit profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: 'delete' %></li>
              </ul>                
            </li>      
          <% else %>
            <li><%= link_to "Sign In", user_session_path, :id => 'signup' %></li>
          <% end %>              
        </ul> 
        </ul>          
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_voting.html.erb
<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= topic.description %></td>
    <td><%= pluralize(topic.votes.count, "vote") %></td>
    <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grxclan</title>
  <%= stylesheet_link_tag    "application", "dropit.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "dropit.js", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %> 

</head>
  
<body>
  <div class="header"><%= render 'layouts/header' %></div>
  <div class="container">	
    <%= yield %>
  </div>
    <script type="text/javascript">$(document).ready(function() {
      $('.menu').dropit();
    });</script>
    <script>document.addEventListener('DOMContentLoaded', function(){
    //   !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs")};
    // </script>

    <script type="text/javascript">$(window).on('load', function() {
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.async=true;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
  });
    </script>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About grX Clan</h1></br>
  <h3>What does grX mean?</h3>
    <p>Gamers Redefining eXcellence - a collaborative community developing gaming skills and synergistic teamwork to overcome any challenge.</p></br>
  <h3>Who is the grX Clan?</h3>
    <p>Just a bunch of young professionals in the marketplace (most of us in Silicon Valley) who game together in the evenings. We've been sharing life together since 2006 and have become lifelong friends who love to shoot at each other's digital avatars.</p>

app/views/static_pages/home.html.erb
<div class="center">
          <% if signed_in? %>
            <p>Welcome <%=current_user.gamertag%>!</p>
          <% end %> 	
    <div id="tweets">
      <h1>Twitter <%= image_tag "Twitter Green.png", alt: "GRXclan Twitter" %></h1>  
      <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/grxclan" data-widget-id="504028506846535681" data-link-color="#30B542" data-chrome="noheader noborders noscrollbar transparent" data-tweet-limit="3" width="250" height="500">Tweets by @grxclan</a>
    </div>      
    <h1>GRX Clan</h1>
    <h2>Gamers Redefining eXcellence</h2>
    <h3>Gears of War 3 Matches: 1v1</h3>
    <p>taeWook vs. hguy4x</p>
    <p>Gears of War 3</p>
    <p>Tonight 8/12/14 @ 9:30p PST</p>
    <p>Don't miss it!</p>
    <h3>Place your bets here:</h3>
<form accept-charset="UTF-8" action="/home/index" method="post">
  <div style="margin:0;     padding:0">
    <input name="utf8" type="hidden" value="&#x2713;" />
    <input name="authenticity_token" type="hidden" value="f755bb0ed134b76c432144748a6d4b7a7ddf2b71" />
  </div>
    <ul class="vote">
      <li>
        <h2>Harvey</h2>
        <%=link_to(image_tag("Randallwong.jpg", :class => "brand"),        
        topics_path(@topic), :remote=> true, :method => :post) %>
        <%= button_to 'I choose Harvey', topics_path(@topic), method: :post %>
      </li>  
	    <li>	
        <h2>Paul</h2>
        <%=link_to(image_tag("Randallwong.jpg", :class => "brand"),        
        topics_path(@topic), :remote=> true, :method => :post) %>
        <%= button_to 'I choose Paul', topics_path(@topic), method: :post %>
      </li>          
      </li>
    </ul>
</form>
</div>

app/views/static_pages/roster.html.erb
      <ul class="roster-list">
        <% @users.each do |user| %> 
          <li>
            <div class="left-profile">
              <h3><%= link_to "#{user.name}", user_path(user.id), method: :get %></h3>
              <%=link_to user_path(user.id) do %>
                <%= image_tag(user.avatar.url, size: "200x150", alt: "#{user.gamertag}'s Profile", :class => "profile-pic") %>
              <% end %>
            </div>
            <div class="left-profile-details">
                <p class="gamertag"><%= user.gamertag%></p>
                <p class="role"><%= user.role %></p>
                <div class="social">
                  <span><%= link_to "https://www.youtube.com/#{user.youtube}" do %> 
                    <%= image_tag("youtube64x64.png", size: "45x55", alt: "YouTube") %>
                  <% end %></span>
                  <span><%= link_to "https://twitter.com/#{user.twitter}" do %> 
                    <%= image_tag("twitter64x64.png", size: "45x55", alt: "Twitter") %>
                  <% end %> </span></br>               
                  <div class="twitch"><%= link_to "http://www.twitch.tv/#{user.twitch}" do %> 
                    <%=image_tag("GlitchIcon_purple.png", size: "45x55", alt: "Twitch") %>
                    <span><%= user.twitch %></span></div>
                  <% end %>
                </div>
            </div>
          </li>
        <% end %>   
      </ul>

<!-- <h2>Currently playing:</h2>
<p>Gears of War 3, Halo 4, COD: Ghosts, Titanfall</p> -->

app/views/static_pages/video.html.erb
<h1>MewieTV!</h1>
<p>Going to use Mike's vids to put here ;)</p>

<iframe width="560" height="345" src="http://www.youtube.com/embed/8u0M44OruHA" frameborder="0" allowfullscreen></iframe>

<iframe width="560" height="345" src="http://www.youtube.com/embed/Qmj2jYeuOhg" frameborder="0" allowfullscreen></iframe>

app/views/topics/index.html.erb
<h1>Do I need this page?</h1>

app/views/users/edit.html.erb
<div class="row">
  <h1>Gamer Profile</h1></br>
  <div class="span6 offset3"> 
    <%= form_for @user, url: {action: "update"}, :method => :POST do |profile| %>
      <%= profile.label :Gamertag %>
      <%= profile.text_field :gamertag %>

      <%= profile.label :Real_Name %>
      <%= profile.text_field :name %>

      <%= profile.label :Clan_Role %>
      <%= profile.text_field :role %>

      <%= profile.label :Real_Life_occupation %>
      <%= profile.text_field :occupation %>   

      <%= profile.label :Favorite_game %>
      <%= profile.text_field :fave_game%>  

      <%= profile.label :First_game_addiction %>
      <%= profile.text_field :game_addiction %>  

      <%= profile.label :Favorite_video_game_character %>
      <%= profile.text_field :fave_character %>  

      <%= profile.label :First_FPS_game_played %>
      <%= profile.text_field :first_fps %>   

      <%= profile.label :Favorite_movie %>
      <%= profile.text_field :fave_movie %>

      <%= profile.label :Hobbies_and_interests%>
      <%= profile.text_area :hobbies %>

      <%= profile.label :Something_not_many_people_know_about_me %>
      <%= profile.text_area :fact %>

      <%= profile.label :Twitter %>
      <%= profile.text_field :twitter %>

      <%= profile.label :YouTube %>
      <%= profile.text_field :youtube %>

      <%= profile.label :Twitch.TV %>
      <%= profile.text_field :twitch %> </br>         

      <%= submit_tag "Update profile", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div> 

app/views/users/new.html.erb
<div class="row">
  <h1>Gamer Profile</h1></br>
  <div class="span6 offset3"> 
    <%= form_for @user, url: {action: "create"}, :method => :POST do |profile| %>
      <%= profile.label :Gamertag %>
      <%= profile.text_field :gamertag %>

        <%= profile.label :Real_Name %>
        <%= profile.text_field :name %>

        <%= profile.label :Clan_Role %>
        <%= profile.text_field :role %>

        <%= profile.label :Real_Life_occupation %>
        <%= profile.text_field :occupation %>   

        <%= profile.label :Favorite_game %>
        <%= profile.text_field :fave_game%>  

        <%= profile.label :First_game_addiction %>
        <%= profile.text_field :game_addiction %>  

        <%= profile.label :Favorite_video_game_character %>
        <%= profile.text_field :fave_character %>  

        <%= profile.label :First_FPS_game_played %>
        <%= profile.text_field :first_fps %>   

        <%= profile.label :Favorite_movie %>
        <%= profile.text_field :fave_movie %>

        <%= profile.label :Hobbies_and_interests%>
        <%= profile.text_area :hobbies %>

        <%= profile.label :Something_not_many_people_know_about_me %>
        <%= profile.text_area :fact %>

        <%= profile.label :Twitter %>
        <%= profile.text_field :twitter %> 

        <%= profile.label :YouTube %>
        <%= profile.text_field :youtube %>

        <%= profile.label :Twitch %>
        <%= profile.text_field :twitch %> </br>  

        <%= profile.submit "Create my profile", class: "btn btn-large btn-primary" %>
      <% end %>
  </div>
</div>   

app/views/users/show.html.erb
<div class="profile_background">
<div class="left-profile" id="center">
  <div class="profile-right-border">
    <h1><%= @user.gamertag %></h1>
      <%= image_tag(@user.avatar.url, size: "200x150", alt: "#{@user.gamertag} Photo", :class => "profile-pic") %>
    <h4><%= @user.role %></h4>  
  </div> 
  <div class="social-profile">
    <%= link_to "https://www.twitter.com/#{@user.twitter}" do %> 
      <%= image_tag("twitter64x64.png", size: "40x50", alt: "Twitter") %>
    <% end %>
    <%= link_to "https://www.youtube.com/#{@user.youtube}" do %> 
      <%= image_tag("youtube64x64.png", size: "40x50", alt: "YouTube") %>
    <% end %>
    <%= link_to "http://www.twitch.tv/#{@user.twitch}" do %> 
      <%=image_tag("GlitchIcon_purple.png", size: "50x50", alt: "Twitch") %>
    <% end %> 
  </div>
</div>
<section class="youtube">
  <iframe width="560" height="315" src="//www.youtube.com/embed/<%=@user.featured_vid%>" frameborder="0" allowfullscreen></iframe>
</section>
<section>
      <ul class="profile-facts">
        <li><b>Name:  </b><%= @user.name %></li>
        <li><b>Real-Life Occupation: </b><%= @user.occupation %></li>
        <li><b>Favorite Video Game: </b><%= @user.fave_game %></li>
        <li><b>First Gaming Addiction: </b><%= @user.game_addiction %></li>
        <li><b>Favorite Video Game Character: </b><%= @user.fave_character %></li>
        <li><b>First FPS Game Played: </b><%= @user.first_fps %></li>
        <li><b>Favorite Movie: </b><%= @user.fave_movie %></li>
        <li><b>Hobbies & Interests: </b><%= @user.hobbies %></li>
        <li><b>Something Not Many People Know About Me: </b><%= @user.fact %></li>
      </ul>   
</section>
</div>

app/views/videos/index.html.erb
<%= form_tag(:video) do %>
<%= label_tag(:url, “Enter youtube url”) %>
<%= text_field_tag(:url) %>
<%= submit_tag(“Enter”) %>
<% end %>

app/views/videos/show.html.erb
<h1>Videos#show</h1>
<p>Find me in app/views/videos/show.html.erb</p>

<iframe width="560" height="345" src="http://www.youtube.com/embed/Idmi6tC5L5s" frameborder="0" allowfullscreen></iframe>